<a href="https://colab.research.google.com/github/LimEunSeop/TIL-MachineLearning-Yahak/blob/master/practice5_multilayer_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 생활코딩 머신러닝 야학 10일차 - 네번째 딥러닝 - 신경망의 완성:히든레이어

## 히든레이어
중간결과를 더 추가하여 모델의 학습효과를 높이는 숨겨진 레이어. activation function 으로 swish 로 사용하는것을 알아두자.

- 보스턴 집값 예측: https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv

- 아이리스 품종 분류: https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv 


In [1]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

## 보스턴 집값 예측

In [2]:
# 1.과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)

# 종속변수, 독립변수
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 
            'rm', 'age', 'dis', 'rad', 'tax',
            'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [3]:
# 2. 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(X) # 히든레이어 activation 함수 swish 쓰기!!
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [4]:
# 모델 구조 확인 : 레이어 확인. Param # : weight, bias 갯수의 합
model.summary()

Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense (Dense)                (None, 10)                140       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [7]:
# 3.데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 2ms/step - loss: 14.0398
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 13.7528
Epoch 3/10
16/16 [==============================] - 0s 2ms/step - loss: 14.1838
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 13.4549
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 13.0165
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 13.7507
Epoch 7/10
16/16 [==============================] - 0s 3ms/step - loss: 13.5788
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 13.9596
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 14.7361
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 13.4692


In [8]:
# 4. 모델을 이용합니다
print(model.predict(독립[:5]))
print(종속[:5])

[[26.92237 ]
 [22.11058 ]
 [28.400055]
 [27.848515]
 [28.078121]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


## 아이리스 품종 분류


In [9]:
# 1.과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)

# 원핫인코딩
아이리스 = pd.get_dummies(아이리스)

# 종속변수, 독립변수
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [10]:
# 2. 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation="swish")(X)
H = tf.keras.layers.Dense(8, activation="swish")(H)
H = tf.keras.layers.Dense(8, activation="swish")(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [11]:
# 모델 구조 확인
model.summary()

Model: "functional_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_3 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_4 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_5 (Dense)              (None, 3)                 27        
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# 3.데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=100)

In [13]:
# 4. 모델을 이용합니다
print(model.predict(독립[0:5]))
print(종속[0:5])

[[9.8366404e-01 1.6331419e-02 4.5170796e-06]
 [9.7945476e-01 2.0539045e-02 6.1998144e-06]
 [9.8008943e-01 1.9901829e-02 8.8090846e-06]
 [9.7659361e-01 2.3393773e-02 1.2583308e-05]
 [9.8328251e-01 1.6711719e-02 5.7082248e-06]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
