<a href="https://colab.research.google.com/github/LimEunSeop/TIL-MachineLearning-Yahak/blob/master/practice4_iris_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 생활코딩 머신러닝 야학 9일차 : 원핫인코딩, 세번째 딥러닝 - 아이리스 품종 분류
## 원핫인코딩
범주형 데이터를 가지는 특성을 범주의 갯수만큼 쪼개어 수치화 하는 작업
- pandas의 get_dummies 함수를 이용합니다.
- 데이터와 일치하는 이름의 컬럼은 1, 그렇지 않은 컬럼은 0으로 세팅됩니다.
- 쪼개어진 특성만큼 퍼셉트론을 생성하고 소프트맥스 함수를 이용하여 0~1사이의 확률값이 나오도록 학습시킵니다.

## 소프트맥스
범주형 데이터를 종속변수로 다루는 모델에서 사용되는 activation function 의 한 종류 입니다. activation function 이란, 퍼셉트론의 출력값을 조정하는 함수입니다.
### 소프트맥스를 사용하는 이유
지금 보면 알다시피 모든 범주 컬럼의 값의 합은 1이다. 1이니까 확률로 계산될 수 있고 합이 고정돼 있으니 모델을 학습시키기 더할나위 없이 좋은 조건이다. 한 컬럼의 값에 전체컬럼 합을 나누면 모든 컬럼을 합했을때 1이 되는 편한 값으로 계산된다. 소프트맥스를 사용하지 않으면 각 컬럼에 대해 일반적인 Identity 활성화 함수를 사용하여 접근해야 하고, 0~1에 근접하기 위해 별 쌩쑈를 다할 것이다. 그리고 모든 컬럼의 합도 1이 아닐 것이다. 너무 비효율적이지 않은가!

## 범주형 데이터의 loss
categorical_crossentropy 를 사용. 아직 자세히 공부하진 말고 이것을 쓴다고만 알고있자.
> 회귀에 사용되는 loss 는 mse 이다.

## 아이리스 품종 분류 실습
- github csv url: https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv 


In [1]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [2]:
# 1.과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [3]:
# 원핫인코딩
인코딩 = pd.get_dummies(아이리스)
인코딩.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [4]:
# 칼럼이름 출력
print(인코딩.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [5]:
# 독립변수, 종속변수
독립 = 인코딩[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 인코딩[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [6]:
# 2. 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy') # accuracy : 사람이 보기 더 편한 척도

In [10]:
# 3.데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.3796 - accuracy: 0.8867
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.3790 - accuracy: 0.9000
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.3784 - accuracy: 0.8933
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.3782 - accuracy: 0.9000
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.3764 - accuracy: 0.8867
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.3759 - accuracy: 0.8933
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.3767 - accuracy: 0.8867
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.3744 - accuracy: 0.9000
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.3742 - accuracy: 0.8933
Epoch 10/10
5/5 [==============================] - 0s 3ms/step - loss: 0.3734 - accuracy: 0.9000


In [11]:
# 모델을 이용합니다. 
# 맨 처음 데이터 5개
print(model.predict(독립[:5]))
print(종속[:5])

# 맨 마지막 데이터 5개
print(model.predict(독립[-5:]))
print(종속[-5:])


[[0.9536972  0.03862043 0.00768238]
 [0.9274948  0.06139312 0.0111121 ]
 [0.9388556  0.05057798 0.01056643]
 [0.9156774  0.07011495 0.01420759]
 [0.9551934  0.03696725 0.00783932]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
[[0.00123454 0.22578098 0.77298445]
 [0.0033895  0.3882369  0.6083736 ]
 [0.00304871 0.32898182 0.66796947]
 [0.00092246 0.1840787  0.81499887]
 [0.00458244 0.36981273 0.62560487]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [12]:
# weights & bias 출력
print(model.get_weights())

[array([[ 0.426308  ,  0.04803345, -0.2740409 ],
       [ 0.46037897, -0.37106237, -0.05341117],
       [-0.8421316 ,  0.31109524,  0.15625529],
       [-2.1193297 , -0.108524  ,  1.8477058 ]], dtype=float32), array([ 0.8370861 ,  0.45308754, -0.80543506], dtype=float32)]
