<a href="https://colab.research.google.com/github/LimEunSeop/MachineLearning-Yahak-TIL/blob/master/%EC%8B%A4%EC%8A%B52_%EB%A0%88%EB%AA%A8%EB%84%A4%EC%9D%B4%EB%93%9C_%ED%8C%90%EB%A7%A4_%EC%98%88%EC%B8%A1_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 레모네이드 판매 예측
- github csv url: https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/lemonade.csv 

In [1]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [2]:
# 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/lemonade.csv'
데이터 = pd.read_csv(파일경로)
데이터.head()

온도  판매량
0  20   40
1  21   42
2  22   44
3  23   46
4  24   48

In [3]:
# 종속변수, 독립변수
독립 = 데이터[['온도']]
종속 = 데이터[['판매량']]
print(독립.shape, 종속.shape)

(6, 1) (6, 1)


In [8]:
# 모델을 만듭니다. (shape 값을 바탕으로)
X = tf.keras.layers.Input(shape=[1]) # keras : 신경망 라이브러리. 뉴런 하나를 생성한다. shape : 독립변수의 갯수에 맞춰 1입력.
Y = tf.keras.layers.Dense(1)(X) # 1 : 종속변수 Column 갯수
model = tf.keras.models.Model(X, Y) # 모델 완성
model.compile(loss='mse') # 모델이 학습하는 방법 정의

In [28]:
# 모델을 학습시킵니다.
model.fit(독립, 종속, epochs=10000, verbose=0) # verbose=0 화면출력 끄기
model.fit(독립, 종속, epochs=10)

Epoch 1/10
1/1 [==============================] - 0s 1ms/step - loss: 1.3858e-04
Epoch 2/10
1/1 [==============================] - 0s 7ms/step - loss: 1.3858e-04
Epoch 3/10
1/1 [==============================] - 0s 966us/step - loss: 1.3858e-04
Epoch 4/10
1/1 [==============================] - 0s 3ms/step - loss: 1.3870e-04
Epoch 5/10
1/1 [==============================] - 0s 2ms/step - loss: 1.3876e-04
Epoch 6/10
1/1 [==============================] - 0s 2ms/step - loss: 1.3884e-04
Epoch 7/10
1/1 [==============================] - 0s 1ms/step - loss: 1.3888e-04
Epoch 8/10
1/1 [==============================] - 0s 1ms/step - loss: 1.3884e-04
Epoch 9/10
1/1 [==============================] - 0s 1ms/step - loss: 1.3882e-04
Epoch 10/10
1/1 [==============================] - 0s 2ms/step - loss: 1.3884e-04


In [29]:
# 모델을 이용합니다.
model.predict(독립)

array([[39.98955 ],
       [41.989033],
       [43.98851 ],
       [45.98799 ],
       [47.987473],
       [49.98695 ]], dtype=float32)

In [31]:
model.predict([[15]])

array([[29.992153]], dtype=float32)

In [32]:
model.predict([[15],[45]])

array([[29.992153],
       [89.97654 ]], dtype=float32)